; Grammar for Lox.
; To generate png: ./bin/kgt -l abnf -e svg < /usr/local/swift/lox/ilox/grammar/lox.abnf | isvg -b white -o lox.png

expression          = expressionBlock

expressionBlock     = conditional *( "," expressionBlock)

conditional         = equality *1( "?" expression ":" conditional )

equality            = comparison *( ( "!=" / "==" ) comparison )

comparison          = term *( ( ">" / ">=" / "<" / "<=" ) term )

term                = factor *( ( "-" / "+" ) factor )

factor              = unary *( ( "/" / "*" ) unary )

unary               = ( "-" / "!" ) unary / primary

primary             = 1*DIGIT "." 1*DIGIT / 1*ALPHA /
                    "true" / "false" / "nil" / "(" expression ")"
