sources:
  - "."
templates:
  - "Templates"
output: "."
args:
  baseName: "Expr"
  types: [
    "Binary": [
      "Expr": "left",
      "Token": "op",
      "Expr": "right"
    ],
    "Grouping": [
      "Expr": "expression"
    ],
    "Literal": [
      "Object": "value"
    ],
    "Unary": [
      "Token": "operator",
      "Expr": "right"
    ]
  ]