name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos:
    runs-on: macos-12
    strategy:
      matrix:
        xcode:
          - "14.0"
    steps:
    - uses: actions/checkout@v2
    - name: Xcode version ${{ matrix.xcode }}
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Dependencies
      run: brew install sourcery
    - name: Code generation
      run: "${GITHUB_WORKSPACE}/scripts/pre-build.sh"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
